import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-sans)'],
        display: ['var(--font-display)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        xs: ['11px', { lineHeight: '1.4' }],
        sm: ['13px', { lineHeight: '1.5' }],
        base: ['15px', { lineHeight: '1.6' }],
        lg: ['18px', { lineHeight: '1.4' }],
        xl: ['20px', { lineHeight: '1.3' }],
        '2xl': ['24px', { lineHeight: '1.2' }],
        '3xl': ['32px', { lineHeight: '1.1' }],
        '4xl': ['44px', { lineHeight: '1.05' }],
        '5xl': ['56px', { lineHeight: '1' }],
      },
      spacing: {
        1: 'var(--spacing-1)',
        2: 'var(--spacing-2)',
        3: 'var(--spacing-3)',
        4: 'var(--spacing-4)',
        5: 'var(--spacing-5)',
        6: 'var(--spacing-6)',
        8: 'var(--spacing-8)',
        10: 'var(--spacing-10)',
        12: 'var(--spacing-12)',
        16: 'var(--spacing-16)',
        20: 'var(--spacing-20)',
        24: 'var(--spacing-24)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
      },
      colors: {
        background: 'var(--color-background)',
        surface: 'var(--color-surface)',
        'surface-raised': 'var(--color-surface-raised)',
        border: 'var(--color-border)',
        'border-strong': 'var(--color-border-strong)',
        foreground: 'var(--color-text-primary)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted': 'var(--color-text-muted)',
        brand: 'var(--color-brand)',
        'brand-hover': 'var(--color-brand-hover)',
        accent: 'var(--color-accent)',
        'accent-foreground': 'var(--color-accent-foreground)',
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        danger: 'var(--color-danger)',
        info: 'var(--color-info)',

        /* Role Badges */
        'role-owner-bg': 'var(--color-role-owner-bg)',
        'role-owner-text': 'var(--color-role-owner-text)',
        'role-manager-bg': 'var(--color-role-manager-bg)',
        'role-manager-text': 'var(--color-role-manager-text)',
        'role-member-bg': 'var(--color-role-member-bg)',
        'role-member-text': 'var(--color-role-member-text)',
        'role-viewer-bg': 'var(--color-role-viewer-bg)',
        'role-viewer-text': 'var(--color-role-viewer-text)',

        /* Status Colors */
        'status-backlog': 'var(--color-status-backlog-bg)',
        'status-backlog-text': 'var(--color-status-backlog-text)',
        'status-todo': 'var(--color-status-todo-bg)',
        'status-todo-text': 'var(--color-status-todo-text)',
        'status-inprogress': 'var(--color-status-inprogress-bg)',
        'status-inprogress-text': 'var(--color-status-inprogress-text)',
        'status-inreview': 'var(--color-status-inreview-bg)',
        'status-inreview-text': 'var(--color-status-inreview-text)',
        'status-done': 'var(--color-status-done-bg)',
        'status-done-text': 'var(--color-status-done-text)',
        'status-blocked': 'var(--color-status-blocked-bg)',
        'status-blocked-text': 'var(--color-status-blocked-text)',
      },
      borderColor: {
        DEFAULT: 'var(--color-border)',
        strong: 'var(--color-border-strong)',
        brand: 'var(--color-brand)',
        accent: 'var(--color-accent)',
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        danger: 'var(--color-danger)',
        info: 'var(--color-info)',
      },
      backgroundColor: {
        overlay: 'var(--color-overlay)',
      },
      transitionDuration: {
        fast: 'var(--duration-fast)',
        base: 'var(--duration-base)',
        slow: 'var(--duration-slow)',
        xslow: 'var(--duration-xslow)',
      },
      transitionTimingFunction: {
        standard: 'var(--easing-standard)',
        decelerate: 'var(--easing-decelerate)',
        accelerate: 'var(--easing-accelerate)',
      },
      animation: {
        shimmer: 'shimmer 2s infinite',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '200% 0' },
          '100%': { backgroundPosition: '-200% 0' },
        },
      },
    },
  },
  plugins: [],
};

export default config;
